### ISSUE TITLE
Add support for the document API

### ISSUE THREAD

**Issue by ricardojmendez** [Taoensso/faraday#103]
We don't yet support the "new" document API. Spinning this out from #91, see [this comment](https://github.com/ptaoussanis/faraday/issues/91#issuecomment-167497219) for more details.

**Comment by joelittlejohn** [comment]
The Document API provides a much more pleasant interaction model for Java developers, however since we're already free to work with 'documents' in Clojureland (our edn literals) I think there's limited value in switching Faraday to the document API. Faraday is already giving developers an experience akin to the document API. 

It could simplify some of the Faraday internals to use the Document API but would also carry a performance cost. If we decided to support both APIs (two different Faraday modes) we'd have a lot more code to maintain here.

I'm going to close this one but we're certainly open to ideas about why it might be good to revisit this.
