### ISSUE TITLE
Support empty strings

### ISSUE THREAD

**Issue by smithtim** [Taoensso/faraday#149]
As of May 2020, DynamoDB supports empty strings: https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/

Can we now allow them in faraday?  Currently it fails with `Invalid DynamoDB value: "" (empty string)`.

**Comment by kipz** [comment]
Thanks for the report @smithtim 

I think it makes sense to add support for this. Is this something you'd be interested in contributing yourself?

**Comment by joelittlejohn** [comment]
A thought about this: there are areas where empty strings are still not allowed, but I think we should avoid trying to identify these inside Faraday and just allow DynamoDB to throw an exception if these rules are broken. It seems safer to do this rather than get smart around whether an empty string should be allowed or not and in what context based on table metadata.

**Comment by smithtim** [comment]
Okay, I've made a PR: #150

**Comment by joelittlejohn** [comment]
Fixed by #150
